// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.3
// source: coupon/v1/coupon.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Coupon_CouponCenter_FullMethodName      = "/api.coupon.v1.Coupon/CouponCenter"
	Coupon_ReceiveCoupon_FullMethodName     = "/api.coupon.v1.Coupon/ReceiveCoupon"
	Coupon_MyCoupon_FullMethodName          = "/api.coupon.v1.Coupon/MyCoupon"
	Coupon_UseCouponValidate_FullMethodName = "/api.coupon.v1.Coupon/UseCouponValidate"
)

// CouponClient is the client API for Coupon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponClient interface {
	CouponCenter(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error)
	ReceiveCoupon(ctx context.Context, in *ReceiveCouponRequest, opts ...grpc.CallOption) (*ReceiveCouponReply, error)
	MyCoupon(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error)
	UseCouponValidate(ctx context.Context, in *CouponUseRequest, opts ...grpc.CallOption) (*CouponUseValidateReply, error)
}

type couponClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponClient(cc grpc.ClientConnInterface) CouponClient {
	return &couponClient{cc}
}

func (c *couponClient) CouponCenter(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error) {
	out := new(CouponListReply)
	err := c.cc.Invoke(ctx, Coupon_CouponCenter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ReceiveCoupon(ctx context.Context, in *ReceiveCouponRequest, opts ...grpc.CallOption) (*ReceiveCouponReply, error) {
	out := new(ReceiveCouponReply)
	err := c.cc.Invoke(ctx, Coupon_ReceiveCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) MyCoupon(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error) {
	out := new(CouponListReply)
	err := c.cc.Invoke(ctx, Coupon_MyCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseCouponValidate(ctx context.Context, in *CouponUseRequest, opts ...grpc.CallOption) (*CouponUseValidateReply, error) {
	out := new(CouponUseValidateReply)
	err := c.cc.Invoke(ctx, Coupon_UseCouponValidate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServer is the server API for Coupon service.
// All implementations must embed UnimplementedCouponServer
// for forward compatibility
type CouponServer interface {
	CouponCenter(context.Context, *CouponListRequest) (*CouponListReply, error)
	ReceiveCoupon(context.Context, *ReceiveCouponRequest) (*ReceiveCouponReply, error)
	MyCoupon(context.Context, *CouponListRequest) (*CouponListReply, error)
	UseCouponValidate(context.Context, *CouponUseRequest) (*CouponUseValidateReply, error)
	mustEmbedUnimplementedCouponServer()
}

// UnimplementedCouponServer must be embedded to have forward compatible implementations.
type UnimplementedCouponServer struct {
}

func (UnimplementedCouponServer) CouponCenter(context.Context, *CouponListRequest) (*CouponListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponCenter not implemented")
}
func (UnimplementedCouponServer) ReceiveCoupon(context.Context, *ReceiveCouponRequest) (*ReceiveCouponReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveCoupon not implemented")
}
func (UnimplementedCouponServer) MyCoupon(context.Context, *CouponListRequest) (*CouponListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyCoupon not implemented")
}
func (UnimplementedCouponServer) UseCouponValidate(context.Context, *CouponUseRequest) (*CouponUseValidateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseCouponValidate not implemented")
}
func (UnimplementedCouponServer) mustEmbedUnimplementedCouponServer() {}

// UnsafeCouponServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServer will
// result in compilation errors.
type UnsafeCouponServer interface {
	mustEmbedUnimplementedCouponServer()
}

func RegisterCouponServer(s grpc.ServiceRegistrar, srv CouponServer) {
	s.RegisterService(&Coupon_ServiceDesc, srv)
}

func _Coupon_CouponCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).CouponCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_CouponCenter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).CouponCenter(ctx, req.(*CouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ReceiveCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ReceiveCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_ReceiveCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ReceiveCoupon(ctx, req.(*ReceiveCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_MyCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).MyCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_MyCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).MyCoupon(ctx, req.(*CouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseCouponValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponUseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseCouponValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseCouponValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseCouponValidate(ctx, req.(*CouponUseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coupon_ServiceDesc is the grpc.ServiceDesc for Coupon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coupon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.coupon.v1.Coupon",
	HandlerType: (*CouponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CouponCenter",
			Handler:    _Coupon_CouponCenter_Handler,
		},
		{
			MethodName: "ReceiveCoupon",
			Handler:    _Coupon_ReceiveCoupon_Handler,
		},
		{
			MethodName: "MyCoupon",
			Handler:    _Coupon_MyCoupon_Handler,
		},
		{
			MethodName: "UseCouponValidate",
			Handler:    _Coupon_UseCouponValidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon/v1/coupon.proto",
}
